openapi: 3.0.0
info:
  title: Inhala
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Servidor local de desarrollo
paths:
  /empleados:
    get:
      summary: Obtiene todos los empleados
      responses:
        '200':
          description: Lista de empleados
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    nombre:
                      type: string
